### ISSUE TITLE
"Autostart" re-enables after using hardware/software "menu" button/"Menu-Launcher" shortcut

### ISSUE THREAD

**Issue by ghost** [vackosar/search-based-launcher-v2#2]
Here is the issue:
- If i disable "Autostart" option, it will be enabled if i use hardware "menu" button;
- If i disable "Autostart" it will be re-enabled when i use "Menu-Launcher" shortcut that is created by app.

I tried to enable "Autostart" and try to disable it with steps above but it stayed enabled so it is the problem in "Autostart" state on certain events.

I'm using the latest app build from f-droid on CM7.2 (Gingerbread 2.3.7).

**Comment by vackosar** [comment]
Thank you for your report. That was original intended behaviour. This behaviour was removed during refactoring. Binaries were yet not released.
