### ISSUE TITLE
Keyboard hiding when exiting apps with back button

### ISSUE THREAD

**Issue by lub** [vackosar/search-based-launcher-v2#4]
Hello,

I've noticed on two devices (Wiko HIGHWAY and Samsung Galaxy S3 Mini), that when you leave an app with the device's back button the keyboard won't show up. When using the home button everything works as accepted.

Best regads
lub

**Comment by vackosar** [comment]
Hi, I am refactoring the app. The keyboard hiding was there because of one of my old devices. I removed the code during refactoring.
